// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [`CreateDatasetConfig`][google.cloud.storageinsights.v1.StorageInsights.CreateDatasetConfig]
///
/// [google.cloud.storageinsights.v1.StorageInsights.CreateDatasetConfig]: <doc:StorageInsightsClient/createDatasetConfig(request:options:)>
public struct CreateDatasetConfigRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Value for parent.
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the requesting object.
  /// If auto-generating ID is enabled on the server-side, remove this field and
  /// `dataset_config_id` from the method_signature of Create RPC
  /// Note: The value should not contain any hyphens.
  public var datasetConfigId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var datasetConfig: DatasetConfig? = nil

  /// Optional. A unique identifier for your request.
  /// Specify the request ID if you need to retry the request.
  /// If you retry the request with the same ID within 60 minutes, the server
  /// ignores the request if it has already completed the original request.
  ///
  /// For example, if your initial request times out and you retry the request
  /// using the same request ID, the server recognizes the original request and
  /// does not process the new request.
  ///
  /// The request ID must be a valid UUID and cannot be a zero UUID
  /// (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateDatasetConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateDatasetConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let datasetConfigId = CodingKeys(stringValue: "datasetConfigId")
    static let datasetConfig = CodingKeys(stringValue: "datasetConfig")
    static let requestId = CodingKeys(stringValue: "requestId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "datasetConfigId",
      "datasetConfig",
      "requestId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .datasetConfigId) {
      self.datasetConfigId = value
    }
    self.datasetConfig = try container.decodeIfPresent(DatasetConfig.self, forKey: .datasetConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.datasetConfigId, forKey: .datasetConfigId)
    try container.encodeIfPresent(self.datasetConfig, forKey: .datasetConfig)
    try container.encode(self.requestId, forKey: .requestId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `CreateDatasetConfigRequest`: `"type.googleapis.com/google.cloud.storageinsights.v1.CreateDatasetConfigRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.CreateDatasetConfigRequest"
  }

  /// Initialize an instance of `CreateDatasetConfigRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.storageinsights.v1.CreateDatasetConfigRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CreateDatasetConfigRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
