// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Options to configure CSV formatted reports.
public struct CSVOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Record separator characters in CSV.
  public var recordSeparator: Swift.String = Swift.String()

  /// Delimiter characters in CSV.
  public var delimiter: Swift.String = Swift.String()

  /// If set, will include a header row in the CSV report.
  public var headerRequired: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CSVOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CSVOptions().with { $0.recordSeparator = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let recordSeparator = CodingKeys(stringValue: "recordSeparator")
    static let delimiter = CodingKeys(stringValue: "delimiter")
    static let headerRequired = CodingKeys(stringValue: "headerRequired")

    static let _knownKeys: Set<Swift.String> = [
      "recordSeparator",
      "delimiter",
      "headerRequired",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recordSeparator) {
      self.recordSeparator = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .delimiter) {
      self.delimiter = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .headerRequired) {
      self.headerRequired = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.recordSeparator, forKey: .recordSeparator)
    try container.encode(self.delimiter, forKey: .delimiter)
    try container.encode(self.headerRequired, forKey: .headerRequired)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.CSVOptions"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
