// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing ReportDetail object. ReportDetail represents metadata of
/// generated reports for a ReportConfig.
/// Next ID: 10
public struct ReportDetail: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of resource. It will be of form
  /// projects/<project>/locations/<location>/reportConfigs/<report-config-id>/reportDetails/<report-detail-id>.
  public var name: Swift.String = Swift.String()

  /// The snapshot time.
  /// All the report data is referenced at this point of time.
  public var snapshotTime: GoogleWKT.WKTTimestamp? = nil

  /// Prefix of the object name of each report's shard. This will have full
  /// prefix except the "extension" and "shard_id".
  /// For example, if the `destination_path` is
  /// `{{report-config-id}}/dt={{datetime}}`, the shard object name would be
  /// `gs://my-insights/1A34-F2E456-12B456-1C3D/dt=2022-05-20T06:35/1A34-F2E456-12B456-1C3D_2022-05-20T06:35_5.csv`
  /// and the value of `report_path_prefix` field would be
  /// `gs://my-insights/1A34-F2E456-12B456-1C3D/dt=2022-05-20T06:35/1A34-F2E456-12B456-1C3D_2022-05-20T06:35_`.
  public var reportPathPrefix: Swift.String = Swift.String()

  /// Total shards generated for the report.
  public var shardsCount: Swift.Int64 = Swift.Int64()

  /// Status of the ReportDetail.
  public var status: GoogleRpc.Status? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// The date for which report is generated. The time part of target_datetime
  /// will be zero till we support multiple reports per day.
  public var targetDatetime: GoogleType.DateTime? = nil

  /// Metrics of the report.
  public var reportMetrics: ReportDetail.Metrics? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReportDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReportDetail().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let snapshotTime = CodingKeys(stringValue: "snapshotTime")
    static let reportPathPrefix = CodingKeys(stringValue: "reportPathPrefix")
    static let shardsCount = CodingKeys(stringValue: "shardsCount")
    static let status = CodingKeys(stringValue: "status")
    static let labels = CodingKeys(stringValue: "labels")
    static let targetDatetime = CodingKeys(stringValue: "targetDatetime")
    static let reportMetrics = CodingKeys(stringValue: "reportMetrics")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "snapshotTime",
      "reportPathPrefix",
      "shardsCount",
      "status",
      "labels",
      "targetDatetime",
      "reportMetrics",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.snapshotTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .snapshotTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reportPathPrefix) {
      self.reportPathPrefix = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .shardsCount) {
      self.shardsCount = value
    }
    self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.targetDatetime = try container.decodeIfPresent(
      GoogleType.DateTime.self, forKey: .targetDatetime)
    self.reportMetrics = try container.decodeIfPresent(
      ReportDetail.Metrics.self, forKey: .reportMetrics)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.snapshotTime, forKey: .snapshotTime)
    try container.encode(self.reportPathPrefix, forKey: .reportPathPrefix)
    try container.encode(self.shardsCount, forKey: .shardsCount)
    try container.encodeIfPresent(self.status, forKey: .status)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.targetDatetime, forKey: .targetDatetime)
    try container.encodeIfPresent(self.reportMetrics, forKey: .reportMetrics)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Different metrics associated with the generated report.
  public struct Metrics: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Count of Cloud Storage objects which are part of the report.
    public var processedRecordsCount: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Metrics`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Metrics().with { $0.processedRecordsCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let processedRecordsCount = CodingKeys(stringValue: "processedRecordsCount")

      static let _knownKeys: Set<Swift.String> = [
        "processedRecordsCount"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .processedRecordsCount)
      {
        self.processedRecordsCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.processedRecordsCount, forKey: .processedRecordsCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.storageinsights.v1.ReportDetail.Metrics"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.ReportDetail"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
