// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "StorageInsightsQuickstart")
public final class StorageInsightsClient: Clients.StorageInsightsProtocol, Sendable {
  let inner: any Clients.StorageInsightsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `StorageInsightsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.StorageInsightsStub = try Clients.StorageInsightsTransport(options)
    inner = Clients.StorageInsightsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.StorageInsightsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists ReportConfigs in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportConfigs")
  public func listReportConfigs(
    request: ListReportConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse {
    try await self.inner.listReportConfigs(request: request, options: options)
  }

  /// Gets details of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_GetReportConfig")
  public func getReportConfig(
    request: GetReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    try await self.inner.getReportConfig(request: request, options: options)
  }

  /// Creates a new ReportConfig in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_CreateReportConfig")
  public func createReportConfig(
    request: CreateReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    try await self.inner.createReportConfig(request: request, options: options)
  }

  /// Updates the parameters of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_UpdateReportConfig")
  public func updateReportConfig(
    request: UpdateReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    try await self.inner.updateReportConfig(request: request, options: options)
  }

  /// Deletes a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_DeleteReportConfig")
  public func deleteReportConfig(
    request: DeleteReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteReportConfig(request: request, options: options)
  }

  /// Lists ReportDetails in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportDetails")
  public func listReportDetails(
    request: ListReportDetailsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse {
    try await self.inner.listReportDetails(request: request, options: options)
  }

  /// Gets details of a single ReportDetail.
  ///
  /// @Snippet(path: "StorageInsights_GetReportDetail")
  public func getReportDetail(
    request: GetReportDetailRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail {
    try await self.inner.getReportDetail(request: request, options: options)
  }

  /// Lists the dataset configurations in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_ListDatasetConfigs")
  public func listDatasetConfigs(
    request: ListDatasetConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse {
    try await self.inner.listDatasetConfigs(request: request, options: options)
  }

  /// Gets the dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_GetDatasetConfig")
  public func getDatasetConfig(
    request: GetDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig {
    try await self.inner.getDatasetConfig(request: request, options: options)
  }

  /// Creates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_CreateDatasetConfig")
  public func createDatasetConfig(
    request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createDatasetConfig(request: request, options: options)
  }

  /// Creates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_CreateDatasetConfig")
  public func createDatasetConfigPollingUntilDone(
    request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> DatasetConfig {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DatasetConfig>.State in
      return try op._extractStatus(DatasetConfig.self)
    }
    let rawOp = try await self.createDatasetConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<DatasetConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UpdateDatasetConfig")
  public func updateDatasetConfig(
    request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateDatasetConfig(request: request, options: options)
  }

  /// Updates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UpdateDatasetConfig")
  public func updateDatasetConfigPollingUntilDone(
    request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> DatasetConfig {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DatasetConfig>.State in
      return try op._extractStatus(DatasetConfig.self)
    }
    let rawOp = try await self.updateDatasetConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<DatasetConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_DeleteDatasetConfig")
  public func deleteDatasetConfig(
    request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDatasetConfig(request: request, options: options)
  }

  /// Deletes a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_DeleteDatasetConfig")
  public func deleteDatasetConfigPollingUntilDone(
    request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteDatasetConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Links a dataset to BigQuery in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_LinkDataset")
  public func linkDataset(
    request: LinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.linkDataset(request: request, options: options)
  }

  /// Links a dataset to BigQuery in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_LinkDataset")
  public func linkDatasetPollingUntilDone(
    request: LinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> LinkDatasetResponse {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LinkDatasetResponse>.State in
      return try op._extractStatus(LinkDatasetResponse.self)
    }
    let rawOp = try await self.linkDataset(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<LinkDatasetResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UnlinkDataset")
  public func unlinkDataset(
    request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.unlinkDataset(request: request, options: options)
  }

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UnlinkDataset")
  public func unlinkDatasetPollingUntilDone(
    request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.unlinkDataset(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageInsights_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "StorageInsights_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageInsights_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageInsights_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageInsights_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageInsights_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `StorageInsightsClient`.
  ///
  /// To mock `StorageInsightsClient` change your functions to receive
  /// `some StorageInsightsProtocol` or `any StorageInsightsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol StorageInsightsProtocol: Sendable {
    /// See `StorageInsightsClient.listReportConfigs`.
    func listReportConfigs(
      request: ListReportConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse

    /// See `StorageInsightsClient.getReportConfig`.
    func getReportConfig(
      request: GetReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.createReportConfig`.
    func createReportConfig(
      request: CreateReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.updateReportConfig`.
    func updateReportConfig(
      request: UpdateReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.deleteReportConfig`.
    func deleteReportConfig(
      request: DeleteReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `StorageInsightsClient.listReportDetails`.
    func listReportDetails(
      request: ListReportDetailsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse

    /// See `StorageInsightsClient.getReportDetail`.
    func getReportDetail(
      request: GetReportDetailRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail

    /// See `StorageInsightsClient.listDatasetConfigs`.
    func listDatasetConfigs(
      request: ListDatasetConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse

    /// See `StorageInsightsClient.getDatasetConfig`.
    func getDatasetConfig(
      request: GetDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfig(
      request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfigPollingUntilDone(
      request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatasetConfig

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfig(
      request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfigPollingUntilDone(
      request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatasetConfig

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfig(
      request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfigPollingUntilDone(
      request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `StorageInsightsClient.linkDataset`.
    func linkDataset(
      request: LinkDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.linkDataset`.
    func linkDatasetPollingUntilDone(
      request: LinkDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> LinkDatasetResponse

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDataset(
      request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDatasetPollingUntilDone(
      request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `StorageInsightsClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `StorageInsightsClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `StorageInsightsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `StorageInsightsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `StorageInsightsClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.StorageInsightsProtocol {
  public func listReportConfigs(request: ListReportConfigsRequest) async throws
    -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse
  {
    try await self.listReportConfigs(request: request, options: .init())
  }

  public func listReportConfigs(
    request: ListReportConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listReportConfigsByItems(
    request: ListReportConfigsRequest
  ) -> some AsyncSequence<ReportConfig, Swift.Error> & Sendable {
    self.listReportConfigsByItems(request: request, options: .init())
  }

  /// Lists ReportConfigs in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportConfigs")
  public func listReportConfigsByItems(
    request: ListReportConfigsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ReportConfig, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.listReportConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listReportConfigsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ReportConfig, Swift.Error> & Sendable {
    let request = ListReportConfigsRequest().with {
      $0.parent = parent
    }
    return self.listReportConfigsByItems(request: request)
  }

  public func getReportConfig(request: GetReportConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportConfig
  {
    try await self.getReportConfig(request: request, options: .init())
  }

  public func getReportConfig(
    request: GetReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getReportConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    let request = GetReportConfigRequest().with {
      $0.name = name
    }
    return try await self.getReportConfig(request: request)
  }

  public func createReportConfig(request: CreateReportConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportConfig
  {
    try await self.createReportConfig(request: request, options: .init())
  }

  public func createReportConfig(
    request: CreateReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createReportConfig(
    parent: Swift.String,
    reportConfig: ReportConfig?,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    let request = CreateReportConfigRequest().with {
      $0.parent = parent
      $0.reportConfig = reportConfig
    }
    return try await self.createReportConfig(request: request)
  }

  public func updateReportConfig(request: UpdateReportConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportConfig
  {
    try await self.updateReportConfig(request: request, options: .init())
  }

  public func updateReportConfig(
    request: UpdateReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateReportConfig(
    reportConfig: ReportConfig?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    let request = UpdateReportConfigRequest().with {
      $0.reportConfig = reportConfig
      $0.updateMask = updateMask
    }
    return try await self.updateReportConfig(request: request)
  }

  public func deleteReportConfig(request: DeleteReportConfigRequest) async throws {
    try await self.deleteReportConfig(request: request, options: .init())
  }

  public func deleteReportConfig(
    request: DeleteReportConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteReportConfig(
    name: Swift.String,
  ) async throws {
    let request = DeleteReportConfigRequest().with {
      $0.name = name
    }
    try await self.deleteReportConfig(request: request)
  }

  public func listReportDetails(request: ListReportDetailsRequest) async throws
    -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse
  {
    try await self.listReportDetails(request: request, options: .init())
  }

  public func listReportDetails(
    request: ListReportDetailsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listReportDetailsByItems(
    request: ListReportDetailsRequest
  ) -> some AsyncSequence<ReportDetail, Swift.Error> & Sendable {
    self.listReportDetailsByItems(request: request, options: .init())
  }

  /// Lists ReportDetails in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportDetails")
  public func listReportDetailsByItems(
    request: ListReportDetailsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ReportDetail, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse in
      var request = request
      request.pageToken = token
      return try await self.listReportDetails(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listReportDetailsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ReportDetail, Swift.Error> & Sendable {
    let request = ListReportDetailsRequest().with {
      $0.parent = parent
    }
    return self.listReportDetailsByItems(request: request)
  }

  public func getReportDetail(request: GetReportDetailRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportDetail
  {
    try await self.getReportDetail(request: request, options: .init())
  }

  public func getReportDetail(
    request: GetReportDetailRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getReportDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail {
    let request = GetReportDetailRequest().with {
      $0.name = name
    }
    return try await self.getReportDetail(request: request)
  }

  public func listDatasetConfigs(request: ListDatasetConfigsRequest) async throws
    -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse
  {
    try await self.listDatasetConfigs(request: request, options: .init())
  }

  public func listDatasetConfigs(
    request: ListDatasetConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDatasetConfigsByItems(
    request: ListDatasetConfigsRequest
  ) -> some AsyncSequence<DatasetConfig, Swift.Error> & Sendable {
    self.listDatasetConfigsByItems(request: request, options: .init())
  }

  /// Lists the dataset configurations in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_ListDatasetConfigs")
  public func listDatasetConfigsByItems(
    request: ListDatasetConfigsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<DatasetConfig, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.listDatasetConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listDatasetConfigsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<DatasetConfig, Swift.Error> & Sendable {
    let request = ListDatasetConfigsRequest().with {
      $0.parent = parent
    }
    return self.listDatasetConfigsByItems(request: request)
  }

  public func getDatasetConfig(request: GetDatasetConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.DatasetConfig
  {
    try await self.getDatasetConfig(request: request, options: .init())
  }

  public func getDatasetConfig(
    request: GetDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDatasetConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig {
    let request = GetDatasetConfigRequest().with {
      $0.name = name
    }
    return try await self.getDatasetConfig(request: request)
  }

  public func createDatasetConfig(request: CreateDatasetConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createDatasetConfig(request: request, options: .init())
  }

  public func createDatasetConfig(
    request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDatasetConfigPollingUntilDone(request: CreateDatasetConfigRequest) async throws
    -> DatasetConfig
  {
    return try await self.createDatasetConfigPollingUntilDone(request: request, options: .init())
  }

  public func createDatasetConfigPollingUntilDone(
    request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> DatasetConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDatasetConfigPollingUntilDone(
    parent: Swift.String,
    datasetConfig: DatasetConfig?,
    datasetConfigId: Swift.String,
  ) async throws -> DatasetConfig {
    let request = CreateDatasetConfigRequest().with {
      $0.parent = parent
      $0.datasetConfig = datasetConfig
      $0.datasetConfigId = datasetConfigId
    }
    return try await self.createDatasetConfigPollingUntilDone(request: request)
  }

  public func updateDatasetConfig(request: UpdateDatasetConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateDatasetConfig(request: request, options: .init())
  }

  public func updateDatasetConfig(
    request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateDatasetConfigPollingUntilDone(request: UpdateDatasetConfigRequest) async throws
    -> DatasetConfig
  {
    return try await self.updateDatasetConfigPollingUntilDone(request: request, options: .init())
  }

  public func updateDatasetConfigPollingUntilDone(
    request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> DatasetConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateDatasetConfigPollingUntilDone(
    datasetConfig: DatasetConfig?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> DatasetConfig {
    let request = UpdateDatasetConfigRequest().with {
      $0.datasetConfig = datasetConfig
      $0.updateMask = updateMask
    }
    return try await self.updateDatasetConfigPollingUntilDone(request: request)
  }

  public func deleteDatasetConfig(request: DeleteDatasetConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteDatasetConfig(request: request, options: .init())
  }

  public func deleteDatasetConfig(
    request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDatasetConfigPollingUntilDone(request: DeleteDatasetConfigRequest) async throws
  {
    try await self.deleteDatasetConfigPollingUntilDone(request: request, options: .init())
  }

  public func deleteDatasetConfigPollingUntilDone(
    request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDatasetConfigPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteDatasetConfigRequest().with {
      $0.name = name
    }
    try await self.deleteDatasetConfigPollingUntilDone(request: request)
  }

  public func linkDataset(request: LinkDatasetRequest) async throws -> GoogleLongRunning.Operation {
    try await self.linkDataset(request: request, options: .init())
  }

  public func linkDataset(
    request: LinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func linkDatasetPollingUntilDone(request: LinkDatasetRequest) async throws
    -> LinkDatasetResponse
  {
    return try await self.linkDatasetPollingUntilDone(request: request, options: .init())
  }

  public func linkDatasetPollingUntilDone(
    request: LinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> LinkDatasetResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func linkDatasetPollingUntilDone(
    name: Swift.String,
  ) async throws -> LinkDatasetResponse {
    let request = LinkDatasetRequest().with {
      $0.name = name
    }
    return try await self.linkDatasetPollingUntilDone(request: request)
  }

  public func unlinkDataset(request: UnlinkDatasetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.unlinkDataset(request: request, options: .init())
  }

  public func unlinkDataset(
    request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func unlinkDatasetPollingUntilDone(request: UnlinkDatasetRequest) async throws {
    try await self.unlinkDatasetPollingUntilDone(request: request, options: .init())
  }

  public func unlinkDatasetPollingUntilDone(
    request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func unlinkDatasetPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = UnlinkDatasetRequest().with {
      $0.name = name
    }
    try await self.unlinkDatasetPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageInsights_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageInsights_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
